# Generated by Django 5.0 on 2024-02-11 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_data',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text="Better do not change in admin panel. Change required in 2 places: user follows, other user's followers", related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow_data',
            name='follows',
            field=models.ManyToManyField(blank=True, help_text="Better do not change in admin panel. Change required in 2 places: user follows, other user's followers", related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
